using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eshop.Models.Database
{
    public static class ProductHelper
    {
        public static IList<Product> GenerateProducts()
        {
            IList<Product> products = new List<Product>()
            {
                new Product()
                {

                    Name = "Cyberpunk",
                    DataTarget="cyberpunk",
                    Price= 50,
                    ImageSrc ="/images/Products/cyberpunk-2077-cz-pc-code-in-a-box-379802.jpg",
                    ImageAlt="cyberpunk",
                    ProductInfo="Cyberpunk 2077 for PC is a first-person shooter game, but one with a difference. Set in a dystopian Free State of California, the rules of the nation and the state no longer apply. Instead, playing as a mercenary named V, the player must work their way around the city, attaining their goals and battling enemies as they go.",
                    DetailInfo="<h2>About the Game</h2><br>" +
                    "Seven years in the making, Cyberpunk 2077 looks to be living up to all the hype generated by its introduction at E3 in 2019. <br><br>" +
                    "Set fifty-seven years after the table-top game upon which it is based, Cyberpunk 2020, the graphics are exquisitely rendered with characters, scenery and even actions and movements so realistic that they could be mistaken for movie footage.<br><br>" +
                    "As you play through the narrative driven game, it is possible to play without killing any other characters, using non-lethal weaponry and strategies that keep you out of serious confrontations of the sort that tend to become lethal.<br><br>" +
                    "The game features full nudity, as players are able to upgrade their bodies with modifications that give them extra powers and capabilities, and they need to strip down in order to fit their new limbs and attachments. <br><br>" +
                    "<h2>New Details</h2><br>" +
                    "One of the biggest unique selling points of this game is the fact that Keanu Reeves is heavily featured in the game. He plays a character called Johnny Silverhand, who is the lead singer from a band, Samurai, whose songs contain lyrics relevant to V’s state of mind and his life.<br><br>" +
                    "Silverhand, an original character from the table-top game, is dead in this time, but ‘lives’ in V’s head. This means that the character has more lines of dialogue than any other character save V, who is the protagonist.<br><br>" +
                    "Reeves was a surprise unveiling when the third trailer dropped, and gave the release date to excited fans, keen to get to grips with the latest offering from CD PROJEKT RED, famous for giving us the beloved Witcher games.<br><br>" +
                    "<h2>Ways to Play</h2><br>" +
                    "•	Skills: You can play your way through the game, relishing the agility that V has on his or her feet (the character is fully customisable as to clothing, gender, size and so much more), racking up a high kill rate as you dodge from behind walls or vehicles to take down your enemies as quickly and accurately as you can.<br><br>" +
                    "•	Smart Rifle: Using the Smart Rifle is a good way to target your enemy. Simply lock on to their avatar, then send a bullet after them. The bullet will pursue the character until it catches up with them. An efficient way to rid yourself of nuisances while getting on with the rest of your mission.<br><br>" +
                    "•	No Kill: There is no moral code on the game, meaning that you can storm through the game killing anyone and everyone who annoys you if that is the way that you like to play. However, there is no need to kill anyone at all. Challenge yourself to work through the game in a non-violent way, trading and dealing with non-playing characters (known as NPCs). <br><br>" +
                    "NPCs are important to the game – take Johnny Silverhand as a case in point – and you can interact with them, befriending and even marrying them. Therefore, the no-kill play method can open up a whole new world for you, introducing you to characters and their backstories in a way that you will not experience should you simply blast them out of your way.<br><br>" +
                    "<h2>Endgame</h2><br>" +
                    "There is no fixed aim for the game. Instead V must travel around the city, working to find health points and mods, avoiding or killing villains and generally just living their best life. Think of it as a world away from the real world: somewhere that you can be someone a little different.<br><br>" +
                    "<br><br><center><img src=\"https://cdn.mos.cms.futurecdn.net/Comh2ySobkMJTgnimk54ta-1200-80.png\" alt=\"Cyberpunk_2077_Standard\" title=\"Cyberpunk_2077_Standard\" frameborder=\"0\"></center><br><br>"
                },
                new Product()
                {
                    Name = "Farming",
                    DataTarget="farming",
                    Price= 28,
                    ImageSrc ="/images/Products/farming-simulator-19-xbox-one-381543.jpg",
                    ImageAlt="farming",
                    ProductInfo="Farming Simulator 19 takes the biggest step forward yet with the franchise's most extensive vehicle roster ever! You'll take control of vehicles and machines faithfully recreated from all the leading brands in the industry, including for the first time John Deere, the largest agriculture machinery company in the world.",
                    DetailInfo="The multimillion-selling franchise takes a giant leap forward for 2018 - the ultimate farming simulation returns this year with a complete overhaul of the graphics engine, offering the most striking and immersive visuals and effects, along with the deepest and most complete farming experience ever on consoles and PC." +
                    "Farming Simulator 19 takes the biggest step forward yet with the franchise's most extensive vehicle roster ever! You'll take control of vehicles and machines faithfully recreated from all the leading brands in the industry, including for the first time John Deere, the largest agriculture machinery company in the world, Case IH, New Holland, Challenger, Fendt, Massey Ferguson, Valtra, Krone, Deutz - Fahr and many more.<br><br>" +
                    "Farming Simulator 19 will feature new American and European environments in which to develop and expand your farm and will introduce many exciting new farming activities, including new machinery and crops with cotton and oat! Tend to your livestock of pigs, cows, sheep, and chickens - or ride your horses for the first time, letting you explore in a brand - new way the vast land around your farm." +
                    "Farming Simulator 19 is the richest and most complete farming experience ever made for consoles and PCs, releasing at the end of the year!."
                },
                new Product()
                {
                    Name = "Battlefield",
                    DataTarget="battlefield",
                    Price= 64,
                    ImageSrc ="/images/Products/battlefield-1-ps4-352476.jpg",
                    ImageAlt="battlefield",
                    ProductInfo="Battlefield 5 for PC behaves possibly much like real war does, with moments of horrendously soul-crushing death followed by ridiculous moments of lethal levity – death by cricket bat, anyone? The first-person shooter is set in the middle of WWII, albeit with some (rather a lot of) historical inaccuracies.",
                    DetailInfo="World War 2 as You've Never Seen It Before<br> Enter mankind’s greatest conflict with Battlefield™ V as the series goes back to its roots in a never-before-seen portrayal of World War 2. Take the fight to unexpected but crucial moments of the war, as Battlefield goes back to where it all began.<br>" +
                    " <br> 64-Player Multiplayer in the Chaos of All-Out War<br> Lead your Company to victory in all-out multiplayer with new experiences like the massive Grand Operations mode. Take on classic modes like Conquest or squad up with friends in the cooperative Combined Arms.<br> <br> Play Untold War Stories<br>" +
                    " Witness human drama set against global combat in the single player War Stories. Ski down Norwegian mountains as you battle for control of nuclear weapon supply lines, join the frontline with the French colonial troops, or go behind enemy lines in North Africa with a band of misfits sent to create mayhem.<br> <br> The Most Physical Battlefield Yet<br> Maneuver through the battlefield using a new soldier move set, fortifications, and mobile tools of destruction.</p>" +
                    "<br><br><center><img  width=\"1000\" src=\"https://imgs.sector.sk/files/novinky/0/2018/4-18-21-45-68/vyzera,-ze-aj-battlefield-5-bu-image-59.jpg\" alt=\"Cyberpunk_2077_Standard\" title=\"Cyberpunk_2077_Standard\" frameborder=\"0\"></center><br><br>"
                },
                new Product()
                {
                    Name = "Sims",
                    DataTarget="sims",
                    Price= 64,
                    ImageSrc ="/images/Products/the-sims-4-zivot-v-meste-cz-pc-dvd-358427.jpg",
                    ImageAlt="sims",
                    ProductInfo="The Sims 4 (Europe) for PC is a life simulation management game, the best - selling game of 2014 and 2015, and at one point topped the charts across all formats.There are many Sims games, from main games like this one to the frequent expansion packs and add - ons: all proving the enduring popularity of the series.",
                     DetailInfo="The Sims 4 (Europe) for PC is a life simulation management game, " +
                    "the best-selling game of 2014 and 2015, and at one point topped the charts across all formats." +
                    " There are many Sims games, from main games like this one to the frequent expansion packs and add-ons:" +
                    " all proving the enduring popularity of the series.<br><br>" +
                    "<h2>About the Game</h2><br>" +
                    "As with the other games and expansion packs in the series," +
                    " you control the life of your Sims completely – or almost completely" +
                    " – as they go through life, buying or building a home, getting a job or getting into the dating scene.<br><br>" +
                    "There were no defined story arcs in the original game, but later expansion packs and add-ons issued " +
                    "challenges to the Sims, giving them missions to perform or career paths to follow." +
                    " This game is still largely a sandbox game which gives you plenty of scope to decide " +
                    "what your Sims should be doing with their lives.<br><br>" +
                    "However, like children, Sims can unexpectedly resist: some of these traits are more coding issues," +
                    " such as going on a date and choosing to sit at opposite ends of the bar, shouting through the crowd" +
                    " to get a flirtation going, while others are just apparent personal quirks, like not using the closest " +
                    "bin and walking a minute or two to find another that they like better!These quirks are engaging and keep your interest on the game:" +
                    " it would be dull if everyone just did what they were told!< br >< br >" +
                    "< h3 > What’s New?</ h3 >< br >" +
                    "  This game takes place in a different setting to the others in the series, opening up new neighbours and terrains to players, " +
                    "whether new to the series or old hands returning to breath new life into their existing Sims.< br >  < br >" +
                    "  Left to themselves Sims will naturally multitask now, as long as the dual chores are feasible, listening to music while washing up," +
                    " or chatting while watching TV.You couldn’t, for example, write a novel and do the ironing at the same time.< br > < br >" +
                    " There are also ‘moodlets’ which put your Sim in a different state of mind: they can be chilled and relaxed, they can be really " +
                    "angry or they can be really excited. This is a great way to make your Sims’ plans feel more real: being excited about a date puts a " +
                    "whole different vibe on the atmosphere of the Sims’ preparations for the date.< br > < br >" +
                    " < h3 > A Bit of Back - Story </ h3 > < br > The game was inspired by a real - life home - rebuilding exercise." +
                    "Game developer, Will Wright, lost all his possessions and home in a fire and had to rebuild his entire life from scratch." +
                    "Going through this process put the idea of a ‘virtual doll house’ into his mind and – after a bit of tweaking – the Sims were born.<br>  <br>" +
                    "Like many innovative ideas that later seem to have always been a sure thing, Wright was turned down by the first publishers he offered " +
                    "the game to.Fortunately, the second found the idea striking and he was on his way.<br><br>" +
                    "<h3>CAS (Create-A-Sim) System</h3><br>Sims in this incarnation are easier than ever to tweak to make them unique," +
                    " and you can now make highly detailed customisations, such as:<br><br>"
                    },
              
                    

            };
            return products;
        }
    }
}


